from response_structures.visualizations import PlotlyFigureParameters
from pydantic import BaseModel, Field

class final_response_structure(BaseModel):
    """
    Represents a structure for a final response generated by consolidating data from database.

    synthesized using retrieval-augmented generation (RAG). The final_response should include only the synthesized  response and must not include the referneces or markdown elements directly. References meta data should be maintained separately in the references attribute.
    """

    response_text: str = Field(
        description=(
            "The synthesized in-depth response generated by aggregating information from sql database. This text should be a valid markdown text."
            "This field contains only the agent's response, without references."
        )
    )
    visualization_info: PlotlyFigureParameters | None = Field(description="Contains visualization information to better explain the data. Can be None if no visualizations are needed", default=None)
