from pydantic import BaseModel, Field


class final_response_structure(BaseModel):
    """
    Represents a structure for a final response generated by consolidating data from database.

    synthesized using retrieval-augmented generation (RAG). The final_response should include only the synthesized  response and must not include the referneces or markdown elements directly. References meta data should be maintained separately in the references attribute.
    """
    response_text: str = Field(
        description=(
            "The synthesized in-depth response generated by aggregating information from sql database. "
            "This field contains only the agent's response, without references, references markdown elements or their markdown representations."
            )
    )